os: linux
dist: xenial
language: python
python: 
  - "2.7"
install:
  - pip install gomill
  - pip install tensorflow
  - pip install numpy
  - pip install pandas
script:
  ./build_gnugo.sh
  python -m unittest discover
