version: 2
jobs:
  pytest:
    docker:
      - image: circleci/python:2.7.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install tensorflow
      - run: ./thirdparty/build_gnugo.sh && pytest
