version: 2
jobs:
  pytest:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install tensorflow
      - run: ./thirdparty/build_gnugo.sh
      - run: pytest

workflows:
  version: 2
  pytest:
    jobs:
      - pytest